<?php

declare(strict_types = 1);

namespace Money\Currency\Resources;

class CurrencyResources implements CurrencyResourcesInterface
{
    private static array $currencies = [
        'AFN' => ['name' => 'Afghani', 'majorUnit' => 2],
        'EUR' => ['name' => 'Euro', 'majorUnit' => 2],
        'ALL' => ['name' => 'Lek', 'majorUnit' => 2],
        'DZD' => ['name' => 'Algerian Dinar', 'majorUnit' => 2],
        'USD' => ['name' => 'US Dollar', 'majorUnit' => 2],
        'AOA' => ['name' => 'Kwanza', 'majorUnit' => 2],
        'XCD' => ['name' => 'East Caribbean Dollar', 'majorUnit' => 2],
        'ARS' => ['name' => 'Argentine Peso', 'majorUnit' => 2],
        'AMD' => ['name' => 'Dram', 'majorUnit' => 2],
        'AWG' => ['name' => 'Aruban Florin', 'majorUnit' => 2],
        'AUD' => ['name' => 'Australian Dollar', 'majorUnit' => 2],
        'AZN' => ['name' => 'Azerbaijani Manat', 'majorUnit' => 2],
        'BSD' => ['name' => 'Bahamian Dollar', 'majorUnit' => 2],
        'BHD' => ['name' => 'Bahraini Dinar', 'majorUnit' => 2],
        'BDT' => ['name' => 'Taka', 'majorUnit' => 2],
        'BBD' => ['name' => 'Barbadian Dollar', 'majorUnit' => 2],
        'BYR' => ['name' => 'Belarusian Ruble', 'majorUnit' => 2],
        'BZD' => ['name' => 'Belize Dollar', 'majorUnit' => 2],
        'XOF' => ['name' => 'CFA Franc BCEAO', 'majorUnit' => 2],
        'BMD' => ['name' => 'Bermudian Dollar', 'majorUnit' => 2],
        'BTN' => ['name' => 'Ngultrum', 'majorUnit' => 2],
        'INR' => ['name' => 'Indian Rupee', 'majorUnit' => 2],
        'BOB' => ['name' => 'Boliviano', 'majorUnit' => 2],
        'BOV' => ['name' => 'Mvdol', 'majorUnit' => 2],
        'BAM' => ['name' => 'Convertible Mark', 'majorUnit' => 2],
        'BWP' => ['name' => 'Pula', 'majorUnit' => 2],
        'NOK' => ['name' => 'Norwegian Krone', 'majorUnit' => 2],
        'BRL' => ['name' => 'Brazilian Real', 'majorUnit' => 2],
        'BND' => ['name' => 'Brunei Dollar', 'majorUnit' => 2],
        'BGN' => ['name' => 'Lev', 'majorUnit' => 2],
        'BIF' => ['name' => 'Burundian Franc', 'majorUnit' => 2],
        'CVE' => ['name' => 'Cape Verdean Escudo', 'majorUnit' => 2],
        'KHR' => ['name' => 'Cambodian Riel', 'majorUnit' => 2],
        'XAF' => ['name' => 'CFA Franc BEAC', 'majorUnit' => 2],
        'CAD' => ['name' => 'Canadian Dollar', 'majorUnit' => 2],
        'KYD' => ['name' => 'Cayman Islands Dollar', 'majorUnit' => 2],
        'CLF' => ['name' => 'Chilean Unidad de Fomento', 'majorUnit' => 2],
        'CLP' => ['name' => 'Chilean Peso', 'majorUnit' => 2],
        'CNY' => ['name' => 'Renminbi', 'majorUnit' => 2],
        'COP' => ['name' => 'Colombian Peso', 'majorUnit' => 2],
        'COU' => ['name' => 'Unit of Account', 'majorUnit' => 2],
        'KMF' => ['name' => 'Comorian Franc', 'majorUnit' => 2],
        'CDF' => ['name' => 'Congolese Franc', 'majorUnit' => 2],
        'NZD' => ['name' => 'New Zealand Dollar', 'majorUnit' => 2],
        'CRC' => ['name' => 'Costa Rican Colón', 'majorUnit' => 2],
        'HRK' => ['name' => 'Croatian Kuna', 'majorUnit' => 2],
        'CUC' => ['name' => 'Cuban Convertible Peso', 'majorUnit' => 2],
        'CUP' => ['name' => 'Cuban Peso', 'majorUnit' => 2],
        'ANG' => ['name' => 'Netherlands Antillean Guilder', 'majorUnit' => 2],
        'CZK' => ['name' => 'Czech Koruna', 'majorUnit' => 2],
        'DKK' => ['name' => 'Danish Krone', 'majorUnit' => 2],
        'DJF' => ['name' => 'Djiboutian Franc', 'majorUnit' => 2],
        'DOP' => ['name' => 'Dominican Peso', 'majorUnit' => 2],
        'EGP' => ['name' => 'Egyptian Pound', 'majorUnit' => 2],
        'SVC' => ['name' => 'Salvadoran Colón', 'majorUnit' => 2],
        'ERN' => ['name' => 'Eritrean Nakfa', 'majorUnit' => 2],
        'ETB' => ['name' => 'Ethiopian Birr', 'majorUnit' => 2],
        'FKP' => ['name' => 'Falkland Islands Pound', 'majorUnit' => 2],
        'FJD' => ['name' => 'Fijian Dollar', 'majorUnit' => 2],
        'XPF' => ['name' => 'CFP Franc', 'majorUnit' => 2],
        'GMD' => ['name' => 'Gambian Dalasi', 'majorUnit' => 2],
        'GEL' => ['name' => 'Georgian Lari', 'majorUnit' => 2],
        'GHS' => ['name' => 'Ghanaian Cedi', 'majorUnit' => 2],
        'GIP' => ['name' => 'Gibraltar Pound', 'majorUnit' => 2],
        'GTQ' => ['name' => 'Guatemalan Quetzal', 'majorUnit' => 2],
        'GBP' => ['name' => 'British Pound Sterling', 'majorUnit' => 2],
        'GNF' => ['name' => 'Guinean Franc', 'majorUnit' => 2],
        'GYD' => ['name' => 'Guyanese Dollar', 'majorUnit' => 2],
        'HTG' => ['name' => 'Haitian Gourde', 'majorUnit' => 2],
        'HNL' => ['name' => 'Honduran Lempira', 'majorUnit' => 2],
        'HKD' => ['name' => 'Hong Kong Dollar', 'majorUnit' => 2],
        'HUF' => ['name' => 'Hungarian Forint', 'majorUnit' => 2],
        'ISK' => ['name' => 'Icelandic Krona', 'majorUnit' => 2],
        'IDR' => ['name' => 'Indonesian Rupiah', 'majorUnit' => 2],
        'XDR' => ['name' => 'Special Drawing Rights (SDR)', 'majorUnit' => 2],
        'IRR' => ['name' => 'Iranian Rial', 'majorUnit' => 2],
        'IQD' => ['name' => 'Iraqi Dinar', 'majorUnit' => 2],
        'ILS' => ['name' => 'Israeli New Shekel', 'majorUnit' => 2],
        'JMD' => ['name' => 'Jamaican Dollar', 'majorUnit' => 2],
        'JPY' => ['name' => 'Japanese Yen', 'majorUnit' => 2],
        'JOD' => ['name' => 'Jordanian Dinar', 'majorUnit' => 2],
        'KZT' => ['name' => 'Kazakhstani Tenge', 'majorUnit' => 2],
        'KES' => ['name' => 'Kenyan Shilling', 'majorUnit' => 2],
        'KPW' => ['name' => 'North Korean Won', 'majorUnit' => 2],
        'KRW' => ['name' => 'South Korean Won', 'majorUnit' => 2],
        'KWD' => ['name' => 'Kuwaiti Dinar', 'majorUnit' => 2],
        'KGS' => ['name' => 'Kyrgyzstani Som', 'majorUnit' => 2],
        'LAK' => ['name' => 'Lao Kip', 'majorUnit' => 2],
        'LBP' => ['name' => 'Lebanese Pound', 'majorUnit' => 2],
        'LSL' => ['name' => 'Lesotho Loti', 'majorUnit' => 2],
        'ZAR' => ['name' => 'Rand', 'majorUnit' => 2],
        'LRD' => ['name' => 'Liberian Dollar', 'majorUnit' => 2],
        'LYD' => ['name' => 'Libyan Dinar', 'majorUnit' => 2],
        'CHF' => ['name' => 'Swiss Franc', 'majorUnit' => 2],
        'MOP' => ['name' => 'Pataca', 'majorUnit' => 2],
        'MKD' => ['name' => 'Macedonian Denar', 'majorUnit' => 2],
        'MGA' => ['name' => 'Ariary', 'majorUnit' => 2],
        'MWK' => ['name' => 'Malawian Kwacha', 'majorUnit' => 2],
        'MYR' => ['name' => 'Ringgit', 'majorUnit' => 2],
        'MVR' => ['name' => 'Maldivian Rufiyaa', 'majorUnit' => 2],
        'MRU' => ['name' => 'Ouguiya', 'majorUnit' => 2],
        'MUR' => ['name' => 'Mauritian Rupee', 'majorUnit' => 2],
        'XUA' => ['name' => 'ADB Unit of Account', 'majorUnit' => 2],
        'MXN' => ['name' => 'Mexican Peso', 'majorUnit' => 2],
        'MXV' => ['name' => 'Mexican Unidad de Inversion (UDI)', 'majorUnit' => 2],
        'MDL' => ['name' => 'Moldovan Leu', 'majorUnit' => 2],
        'MNT' => ['name' => 'Tugrik', 'majorUnit' => 2],
        'MAD' => ['name' => 'Moroccan Dirham', 'majorUnit' => 2],
        'MZN' => ['name' => 'Mozambican Metical', 'majorUnit' => 2],
        'MMK' => ['name' => 'Kyat', 'majorUnit' => 2],
        'NAD' => ['name' => 'Namibian Dollar', 'majorUnit' => 2],
        'NPR' => ['name' => 'Nepalese Rupee', 'majorUnit' => 2],
        'NIO' => ['name' => 'Cordoba Oro', 'majorUnit' => 2],
        'NGN' => ['name' => 'Naira', 'majorUnit' => 2],
        'OMR' => ['name' => 'Omani Rial', 'majorUnit' => 2],
        'PKR' => ['name' => 'Pakistani Rupee', 'majorUnit' => 2],
        'PAB' => ['name' => 'Balboa', 'majorUnit' => 2],
        'PGK' => ['name' => 'Kina', 'majorUnit' => 2],
        'PYG' => ['name' => 'Guarani', 'majorUnit' => 2],
        'PEN' => ['name' => 'Sol', 'majorUnit' => 2],
        'PHP' => ['name' => 'Philippine Peso', 'majorUnit' => 2],
        'PLN' => ['name' => 'Zloty', 'majorUnit' => 2],
        'QAR' => ['name' => 'Qatari Rial', 'majorUnit' => 2],
        'RON' => ['name' => 'Romanian Leu', 'majorUnit' => 2],
        'RUB' => ['name' => 'Russian Ruble', 'majorUnit' => 2],
        'RWF' => ['name' => 'Rwandan Franc', 'majorUnit' => 2],
        'SHP' => ['name' => 'Saint Helena Pound', 'majorUnit' => 2],
        'WST' => ['name' => 'Samoan Tala', 'majorUnit' => 2],
        'STN' => ['name' => 'Dobra', 'majorUnit' => 2],
        'SAR' => ['name' => 'Saudi Riyal', 'majorUnit' => 2],
        'RSD' => ['name' => 'Serbian Dinar', 'majorUnit' => 2],
        'SCR' => ['name' => 'Seychellois Rupee', 'majorUnit' => 2],
        'SLL' => ['name' => 'Leone', 'majorUnit' => 2],
        'SGD' => ['name' => 'Singapore Dollar', 'majorUnit' => 2],
        'XSU' => ['name' => 'Sucre', 'majorUnit' => 2],
        'SBD' => ['name' => 'Solomon Islands Dollar', 'majorUnit' => 2],
        'SOS' => ['name' => 'Somali Shilling', 'majorUnit' => 2],
        'SSP' => ['name' => 'South Sudanese Pound', 'majorUnit' => 2],
        'LKR' => ['name' => 'Sri Lankan Rupee', 'majorUnit' => 2],
        'SDG' => ['name' => 'Sudanese Pound', 'majorUnit' => 2],
        'SRD' => ['name' => 'Surinamese Dollar', 'majorUnit' => 2],
        'SZL' => ['name' => 'Lilangeni', 'majorUnit' => 2],
        'SEK' => ['name' => 'Swedish Krona', 'majorUnit' => 2],
        'CHE' => ['name' => 'WIR Euro', 'majorUnit' => 2],
        'CHW' => ['name' => 'WIR Franc', 'majorUnit' => 2],
        'SYP' => ['name' => 'Syrian Pound', 'majorUnit' => 2],
        'TWD' => ['name' => 'New Taiwan Dollar', 'majorUnit' => 2],
        'TJS' => ['name' => 'Somoni', 'majorUnit' => 2],
        'TZS' => ['name' => 'Tanzanian Shilling', 'majorUnit' => 2],
        'THB' => ['name' => 'Baht', 'majorUnit' => 2],
        'TOP' => ['name' => 'Pa’anga', 'majorUnit' => 2],
        'TTD' => ['name' => 'Trinidad and Tobago Dollar', 'majorUnit' => 2],
        'TND' => ['name' => 'Tunisian Dinar', 'majorUnit' => 2],
        'TRY' => ['name' => 'Turkish Lira', 'majorUnit' => 2],
        'TMT' => ['name' => 'Turkmenistani Manat', 'majorUnit' => 2],
        'UGX' => ['name' => 'Ugandan Shilling', 'majorUnit' => 2],
        'UAH' => ['name' => 'Hryvnia', 'majorUnit' => 2],
        'AED' => ['name' => 'UAE Dirham', 'majorUnit' => 2],
        'USN' => ['name' => 'United States Dollar (Next day)', 'majorUnit' => 2],
        'UYI' => ['name' => 'Uruguay Peso', 'majorUnit' => 2],
        'UYU' => ['name' => 'Uruguayan Peso', 'majorUnit' => 2],
        'UZS' => ['name' => 'Uzbekistan Sum', 'majorUnit' => 2],
        'VUV' => ['name' => 'Vatu', 'majorUnit' => 2],
        'VEF' => ['name' => 'Bolívar', 'majorUnit' => 2],
        'VND' => ['name' => 'Dong', 'majorUnit' => 2],
        'YER' => ['name' => 'Yemeni Rial', 'majorUnit' => 2],
        'ZMW' => ['name' => 'Zambian Kwacha', 'majorUnit' => 2],
        'ZWL' => ['name' => 'Zimbabwean Dollar', 'majorUnit' => 2],
    ];

    /**
     * @return array<string, array>
     */
    public static function get(): array
    {
        foreach (self::$currencies as $code => $currency) {
            if (is_string($code) && isset($currency['name'], $currency['majorUnit']) && is_string($currency['name']) && is_int($currency['majorUnit'])) {
                continue;
            }

            throw new \ErrorException("Currency data for '$code' is not valid");
        }

        return self::$currencies;
    }
}
